// Ensure Prism global is set before loading language grammars for SSR.
import "./utils/prism.js";
import "prismjs/components/prism-javascript";
import "prismjs/components/prism-jsx";
import "prismjs/components/prism-typescript";
import "prismjs/components/prism-tsx";
import "prismjs/components/prism-sql";
import "prismjs/components/prism-json";
import "prismjs/components/prism-bash";
import "prismjs/components/prism-diff";

import {jsx} from "@b9g/crank/standalone";
import {renderer} from "@b9g/crank/html";
import {Router} from "@b9g/router";
import {trailingSlash} from "@b9g/router/middleware";
import {assets as assetsMiddleware} from "@b9g/assets/middleware";

import {collectDocuments, type DocInfo} from "./models/document.js";

import HomeView from "./views/home.js";
import GuideView from "./views/guide.js";
import NotFoundView from "./views/not-found.js";

// Content-hashed asset imports.
import clientCSS from "./styles/client.css" with {assetBase: "/static/"};
import navbarScript from "./clients/navbar.ts" with {assetBase: "/static/"};
import searchScript from "./clients/search.ts" with {assetBase: "/static/"};
import copyScript from "./clients/copy.ts" with {assetBase: "/static/"};
import staticFiles from "../static/**/*" with {
	assetBase: "/static/",
	assetName: "[name].[ext]",
};

export const SITE_URL = "https://zendb.org";

export const logger = self.loggers.get(["app", "zen-website"]);

// Asset URLs for use in views. `ogImage` is optional — only present when the
// PNG logo set has been generated via `bun run build-logo`.
export const assets = {
	clientCSS,
	navbarScript,
	searchScript,
	copyScript,
	logo: staticFiles["logo.svg"],
	ogImage: staticFiles["logo-512.png"] as string | undefined,
};

const router = new Router();

const requestLogger = self.loggers.get(["app", "zen-website"]);
router.use(async (request) => {
	const url = new URL(request.url);
	requestLogger.info("{method} {path}", {
		method: request.method,
		path: url.pathname,
	});
	return;
});

// Append trailing slashes (redirect /path -> /path/).
router.use(trailingSlash("append"));

// Serve /static/ hashed files.
router.use(assetsMiddleware());

// Serve pagefind files (generated by the static build).
router.route("/pagefind/:path*").get(async (request, context) => {
	try {
		const pagefindDir = await self.directories.open("pagefind");
		const pathStr = context.params.path || "";
		const parts = pathStr.split("/").filter(Boolean);

		let currentDir = pagefindDir;
		for (let i = 0; i < parts.length - 1; i++) {
			currentDir = await currentDir.getDirectoryHandle(parts[i]);
		}

		const fileName = parts[parts.length - 1] || "";
		const fileHandle = await currentDir.getFileHandle(fileName);
		const file = await fileHandle.getFile();
		const content = await file.arrayBuffer();
		const dotIndex = fileName.lastIndexOf(".");
		const ext = dotIndex !== -1 ? fileName.slice(dotIndex).toLowerCase() : "";
		const contentType =
			ext === ".js"
				? "application/javascript"
				: ext === ".css"
					? "text/css"
					: "application/octet-stream";

		return new Response(content, {
			headers: {"Content-Type": contentType},
		});
	} catch {
		return new Response("Not Found (run static build first)", {status: 404});
	}
});

async function renderView(
	View: any,
	url: string,
	params: Record<string, string> = {},
): Promise<Response> {
	if (!url.endsWith("/")) {
		url = url + "/";
	}

	const html = await renderer.render(jsx`
		<${View} url=${url} params=${params} />
	`);

	return new Response(html, {
		headers: {"Content-Type": "text/html"},
	});
}

// Routes
router.route("/").get(async (request) => {
	const url = new URL(request.url);
	return renderView(HomeView, url.pathname);
});

router.route("/guides/:slug/").get(async (request, context) => {
	const url = new URL(request.url);
	return renderView(GuideView, url.pathname, context.params);
});

const robotsTxt = `User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;

router.route("/robots.txt").get(async () => {
	return new Response(robotsTxt, {
		headers: {"Content-Type": "text/plain"},
	});
});

router.route("/sitemap.xml").get(async () => {
	const docsDir = await self.directories.open("docs");
	const guideDocs = await collectDocuments(
		await docsDir.getDirectoryHandle("guides"),
		"guides",
	);

	const urls = ["/"];
	for (const doc of guideDocs) {
		if (doc.attributes.publish) urls.push(doc.url);
	}

	return new Response(generateSitemap(urls), {
		headers: {"Content-Type": "application/xml"},
	});
});

// 404 catch-all (must be last).
router.route("*").all(async (request) => {
	const url = new URL(request.url);
	const html = await renderer.render(jsx`
		<${NotFoundView} url=${url.pathname} params=${{}} />
	`);
	return new Response(html, {
		status: 404,
		headers: {"Content-Type": "text/html"},
	});
});

self.addEventListener("fetch", (event) => {
	event.respondWith(router.handle(event.request));
});

self.addEventListener("install", (event) => {
	event.waitUntil(generateStaticSite());
});

async function generateStaticSite() {
	if (import.meta.env.MODE !== "production") {
		return;
	}

	logger.info("Starting static site generation...");

	try {
		const staticBucket = await self.directories.open("public");

		const staticRoutes = ["/"];

		const docsDir = await self.directories.open("docs");
		const guidesDir = await docsDir.getDirectoryHandle("guides");
		const guideDocs = await collectDocuments(guidesDir, "guides");
		staticRoutes.push(
			...guideDocs.filter((d) => d.attributes.publish).map((doc) => doc.url),
		);

		logger.info(`Pre-rendering ${staticRoutes.length} routes...`);

		// Generate 404 page.
		const notFoundResponse = await fetch("/404.html");
		const notFoundHtml = await notFoundResponse.text();
		await writeFile(staticBucket, "404.html", notFoundHtml);
		logger.info("Generated 404.html");

		for (const route of staticRoutes) {
			try {
				const response = await fetch(route);
				if (response.ok) {
					const content = await response.text();
					const filePath =
						route === "/" ? "index.html" : `${route.slice(1)}index.html`;
					await writeFile(staticBucket, filePath, content);
					logger.info(`Generated ${route} -> ${filePath}`);
				}
			} catch (error: any) {
				logger.error(`Failed to generate ${route}:`, error.message);
			}
		}

		await writeFile(staticBucket, "sitemap.xml", generateSitemap(staticRoutes));
		logger.info("Generated sitemap.xml");

		await writeFile(staticBucket, "robots.txt", robotsTxt);
		logger.info("Generated robots.txt");

		logger.info("Static site generation complete!");
	} catch (error: any) {
		logger.error("Static site generation failed: {error}", {error});
	}
}

async function writeFile(
	bucket: FileSystemDirectoryHandle,
	filePath: string,
	content: string | ArrayBuffer,
): Promise<void> {
	const parts = filePath.split("/");
	let currentDir = bucket;
	for (let i = 0; i < parts.length - 1; i++) {
		currentDir = await currentDir.getDirectoryHandle(parts[i], {create: true});
	}
	const fileHandle = await currentDir.getFileHandle(parts[parts.length - 1], {
		create: true,
	});
	const writable = await fileHandle.createWritable();
	await writable.write(content);
	await writable.close();
}

function generateSitemap(urls: string[]): string {
	const entries = urls
		.map((url) => `  <url><loc>${SITE_URL}${url}</loc></url>`)
		.join("\n");
	return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

// Re-exported so views can reference doc types without a separate import.
export type {DocInfo};
